[supervisord]
nodaemon=true
user=container

[program:web]
command=php -S 0.0.0.0:%(ENV_SERVER_PORT)s -t /home/container/src/public
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
priority=10

[program:queue]
command=php /home/container/src/service.php
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
priority=20